apiVersion: apps/v1
kind: Deployment
metadata:
  name: prediction-service
spec:
  selector:
    matchLabels:
      app: prediction-service
  template:
    metadata:
      labels:
        app: prediction-service
    spec:
      containers:
      - name: prediction-service
        image: adjoe-task:0.1.0
        resources:
          limits:
            memory: "1Gi"
          requests:
            memory: "128Mi"
            cpu: 250m
        ports:
        - containerPort: 8000
